### ISSUE TITLE
HibouImageProcessor and HibouModel not found in transformers library

### ISSUE THREAD

**Issue by kaczmarj** [HistAI/hibou#5]
hello, thanks very much for providing a pathology foundation model. i am attempting to use the hibou-L model via huggingface. i attempted to use the instructions on the readme in this repo, which mention `HibouImageProcessor` and `HibouModel`. however, i cannot find these classes in the latest version of `transformers` (4.45.2).

the instructions on huggingface for hibou-L use `AutoModel` instead, which works. i can update the readme in this github repo to use those instructions, if you are interested in that.

### Code

i ran this on google colab

```python
import transformers
print(transformers.__version__)
from transformers import HibouImageProcessor, HibouModel
```

### Outputs and error

```python
4.45.2
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

[<ipython-input-6-1f6eba113776>](https://localhost:8080/#) in <cell line: 3>()
      1 import transformers
      2 print(transformers.__version__)  # 4.45.2
----> 3 from transformers import HibouImageProcessor, HibouModel

ImportError: cannot import name 'HibouImageProcessor' from 'transformers' 
(/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)
```

**Comment by megavaz** [comment]
Hello, you need to use this approach
```
from transformers import AutoImageProcessor, AutoModel

processor = AutoImageProcessor.from_pretrained("histai/hibou-L", trust_remote_code=True)
model = AutoModel.from_pretrained("histai/hibou-L", trust_remote_code=True)
```
or
```
from transformers import AutoImageProcessor, AutoModel

processor = AutoImageProcessor.from_pretrained("histai/hibou-b", trust_remote_code=True)
model = AutoModel.from_pretrained("histai/hibou-b", trust_remote_code=True)
```

**Comment by kaczmarj** [comment]
yes i realize that. but the README has incorrect instructions in this case.

https://github.com/HistAI/hibou/blob/d31873c1e3a6a4b827c4ebd32fa11cca4c8ab947/README.md?plain=1#L33-L36

**Comment by megavaz** [comment]
Oh, thanks for pointing out!

**Comment by kaczmarj** [comment]
great, thank @megavaz !

closed by https://github.com/HistAI/hibou/commit/c453bbe4dab0fec6f7df343b09ea87048629c58d
