### ISSUE TITLE
CellViT-Hibou trained at which resolution

### ISSUE THREAD

**Issue by biototem** [HistAI/hibou#6]
Hi,
Thank you for the excellent work on Hibou and CellViT-Hibou. Since the original CellViT is available in both 40X and 20X versions, could you please clarify which resolution CellViT-Hibou was trained on?

**Comment by megavaz** [comment]
Hi, we've trained the model on the same dataset as the original CellViT so should be 40X.

From the original PanNuke paper:
```
WSIs may have been scanned with a maximum resolution
of either 20× or 40×. We re-sized the selected visual fields so
that all images were at 40× resolution.
```

**Comment by biototem** [comment]
Got it, thanks!
